### ISSUE TITLE
Error occurs if Log folder is not created on initial run

### ISSUE THREAD

**Issue by kim-do-hyeon** [Memori-al/bash-scripts#2]
bash-scripts/sm-shell/Resource/Scripts/settings.sh
`log_path="/sm-shell/Log"`

There is a possibility that an error will occur in the 32nd line, `>> $log_path`, when the shell is executed and `apm install` is added as a print value.

It looks good to add a code to check the presence or absence of a directory to the settings.sh.

```
if[! -d "Log"]; then
 mkdir Log
fi
```

**Comment by Memori-al** [comment]
감사합니다 해결 했습니다.
if [[ ! -d "/sm-shell/Log" ]]; then
    mkdir /sm-shell/Log
fi
